url: https://y7kim.github.io
baseurl: 

# Site settings
title: Ardissone
email: family@ardiss.one
description: ""


# Team names, titles and social links
people:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:

# Build settings
markdown: kramdown
permalink: pretty